title: jupier.github.io
github_username:  jupier
repository: jupier/jupier.github.io

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      related: true
      read_time: true
      toc: true
      toc_sticky: true
      author_profile: true
      author: Me

paginate: 5 # amount of posts to show
paginate_path: /page:num/

atom_feed:
  hide: true

plugins:
  - jekyll-include-cache
  - jekyll-paginate

whitelist:
  - jekyll-include-cache
  - jekyll-paginate

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"